//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NganHangTracNghiem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answer
    {
        public long Id { get; set; }
        public Nullable<long> QuestionId { get; set; }
        public string Content { get; set; }
        public Nullable<int> Order { get; set; }
        public Nullable<bool> Correct { get; set; }
        public Nullable<bool> Interchange { get; set; }
    
        public virtual Question Question { get; set; }
    }
}
