//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NganHangTracNghiem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatrixDetail
    {
        public int Id { get; set; }
        public Nullable<long> MatrixId { get; set; }
        public int ChapterId { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Excluded { get; set; }
    
        public virtual Matrix Matrix { get; set; }
    }
}
