//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NganHangTracNghiem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionSheetDetail
    {
        public long QuestionSheetId { get; set; }
        public long QuestionId { get; set; }
        public Nullable<int> Order { get; set; }
        public Nullable<int> AnswerId { get; set; }
        public Nullable<bool> Correct { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> ListenTimes { get; set; }
    
        public virtual Question Question { get; set; }
        public virtual QuestionSheet QuestionSheet { get; set; }
    }
}
