//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NganHangTracNghiem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Question()
        {
            this.Answers = new HashSet<Answer>();
            this.QuestionSheetDetails = new HashSet<QuestionSheetDetail>();
        }
    
        public long Id { get; set; }
        public string Content { get; set; }
        public Nullable<bool> Interchange { get; set; }
        public Nullable<decimal> SubjectiveDifficulty { get; set; }
        public Nullable<int> SelectedTimes { get; set; }
        public Nullable<int> CorrectTimes { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public int ChapterId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<decimal> Mark { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<long> ParentId { get; set; }
        public Nullable<bool> Audio { get; set; }
        public Nullable<decimal> Discrimination { get; set; }
        public Nullable<int> ManagementOrder { get; set; }
        public Nullable<int> SubjectId { get; set; }
        public Nullable<int> ListenedTimes { get; set; }
        public Nullable<decimal> ObjectiveDifficulty { get; set; }
        public Nullable<int> UserId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Answer> Answers { get; set; }
        public virtual Chapter Chapter { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuestionSheetDetail> QuestionSheetDetails { get; set; }
    }
}
