//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NganHangTracNghiem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionSheet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QuestionSheet()
        {
            this.QuestionSheetDetails = new HashSet<QuestionSheetDetail>();
            this.ShiftSubjectStudents = new HashSet<ShiftSubjectStudent>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<bool> Approved { get; set; }
        public Nullable<bool> Started { get; set; }
        public Nullable<bool> Completed { get; set; }
        public Nullable<int> ExtraTime { get; set; }
        public string ExtraTimeReason { get; set; }
        public Nullable<decimal> Mark { get; set; }
        public Nullable<long> ShiftSubjectStudentId { get; set; }
        public Nullable<int> NumberOfCorrect { get; set; }
        public Nullable<int> Total { get; set; }
        public Nullable<decimal> Difficulty { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuestionSheetDetail> QuestionSheetDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShiftSubjectStudent> ShiftSubjectStudents { get; set; }
    }
}
