//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NganHangTracNghiem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShiftSubjectStudent
    {
        public long ShiftSubjectId { get; set; }
        public int StudentId { get; set; }
        public Nullable<long> QuestionSheetId { get; set; }
        public Nullable<bool> LogIn { get; set; }
        public Nullable<bool> LastLogIn { get; set; }
        public Nullable<bool> LastLogOut { get; set; }
    
        public virtual QuestionSheet QuestionSheet { get; set; }
        public virtual ShiftSubject ShiftSubject { get; set; }
        public virtual Student Student { get; set; }
    }
}
