//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NganHangTracNghiem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shift
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Shift()
        {
            this.ShiftSubjects = new HashSet<ShiftSubject>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<bool> Activated { get; set; }
        public Nullable<System.DateTime> ActivateTime { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<bool> Ended { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> ExamId { get; set; }
        public Nullable<bool> QuestionSheetCreated { get; set; }
        public Nullable<bool> Deleted { get; set; }
    
        public virtual Exam Exam { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShiftSubject> ShiftSubjects { get; set; }
    }
}
